language: node_js
node_js:
  - '12'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
after_success:
  - yarn report-coverage
cache:
  directory:
    - $HOME/.yarn/bin
